version: '3.6'

services:
  land-backend:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: land-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shared-net
    command: bash -c "yarn run prisma migrate dev && yarn run start"
    ports:
      - ${DOCKER_PORT?}:3000

volumes:
  land-db-data:
networks:
  shared-net:
    name: shared-net
    external: true
