export enum ACTIONS {
  READ = 'Read',
  READ_ONE = 'ReadOne',
  CREATE = 'Create',
  UPDATE = 'Update',
  DELETE = 'Delete',
  REJECT = 'Reject',
  APPROVE = 'Approve',
  VERIFY = 'Verify',
  VALIDATE = 'Validate',
  AUTHORIZE = 'Authorize',
  CLOSE = 'Close',
  ARCHIVE = 'Archive',
  REGISTER_PLOT = 'RegisterPlot',
}
